bffbook/bffbook/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home_view'),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

bffbook/posts/urls.py
from django.urls import path
from .views import post_comment_create_and_list_view,like_unlike_post,PostDeleteView,PostUpdateView
app_name='posts'
urlpatterns = [
    path('', post_comment_create_and_list_view, name='main-post-view'),
    path('liked/', like_unlike_post, name='like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(),name='post-update'),
]

bffbook/profiles/urls.py
from django.urls import path
from .views import (
                    my_profile_view,
                    invites_received_view,
                    profiles_list_view,
                    invite_profiles_list_view,
                    ProfileListView,
                    send_invatation,
                    remove_from_friends,
                    )
app_name='profiles'
urlpatterns = [
    path('', my_profile_view, name='my-profile-view'),
    path('my-invites/', invites_received_view, name='my-invites-view'),
    path('all-profiles/',ProfileListView.as_view(), name='all-profiles-view'),
    path('to-invite/', invite_profiles_list_view, name='intive-profiles-view'),
    path('send-invite/', send_invatation, name='send-invite'),
    path('remode-friend/', remove_from_friends, name='remove-friend'),
]

bffbook/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.db.models import Q
class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)

        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile))
        print('-----------')
        print('profiles: ', profiles)
        print('-----------')
        print('profile: ', profile)
        print('-----------')
        print('qs: ', qs)
        print('-----------')
        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print('accepted: ', accepted)
        print('-----------')
        available = [profile for profile in profiles if profile not in accepted]
        print('-----------')
        print('availe: ', available)
        print('-----------')
        return available
        
    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


# Create your models here.
class Profile(models.Model):
    first_name=models.CharField(max_length=200,blank=True)
    last_name =models.CharField(max_length=200,blank=True)
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    bio=models.TextField(default='no bio...',max_length=3000)
    email=models.EmailField(max_length=200,blank=True)
    country=models.CharField(max_length=200,blank=True)
    avatar=models.ImageField(default='avatar.jpg',upload_to='avatars/')
    friends=models.ManyToManyField(User,blank=True,related_name='friends')
    slug=models.SlugField(unique=True,blank=True)
    updated=models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = ProfileManager(
    )
    def get_friends(self):
        return self.friends.all()
    def get_friends_no(self):
        return self.friends.all().count()

    def get_posts_no(self):
        return self.posts.all().count()

    def get_all_authors_post(self):
        return self.posts.all()
    
    def get_likes_given_no(self):
        likes = self.like_set.all()
        print('likes',likes)
        total_liked = 0
        for item in likes:
            
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_received_no(self):
        posts = self.posts.all()
        total_liked = 0
        for item in posts:
            total_liked += item.liked.all().count()
        return total_liked

    def __str__(self):
        return f"{self.user.username}-{self.created.strftime('%d-%m-%Y')}"
    
    def save(self, *args, **kwargs):
        ex = False
        if self.first_name and self.last_name:
            to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
            ex = Profile.objects.filter(slug=to_slug).exists()
            while ex:
                to_slug = slugify(to_slug + " " + str(get_random_code()))
                ex = Profile.objects.filter(slug=to_slug).exists()
        else:
            to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted','accepted')
)

class RelationshipManager(models.Manager):
    def invatations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs
    



class Relationship(models.Model):
    sender = models.ForeignKey(Profile, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(Profile, related_name='receiver', on_delete=models.CASCADE)
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated=models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()
    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"
    
    

bffbook/profiles/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')
    

bffbook/profiles/views.py
from django.shortcuts import render,redirect
from .models import Profile,Relationship
from .forms import ProfileModelForm
from django.views.generic import ListView
from django.contrib.auth.models import User
from django.db.models import Q
# Create your views here.
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True
            
    context = {
        'profile': profile,
        'form': form,
        'confirm':confirm,
    }
    return render(request, 'profiles/myprofile.html', context=context)
def invites_received_view(request):
    profile = Profile.objects.get(user=request.user) 
    qs = Relationship.objects.invatations_received(profile)
    context = {
        'qs':qs
    }
    return render(request, 'profiles/my_invites.html', context=context)



def invite_profiles_list_view(request):
    user=request.user
    qs = Profile.objects.get_all_profiles_to_invite(user)
    context = {
        'qs':qs
    }
    return render(request, 'profiles/to_intive_list.html', context=context)

def profiles_list_view(request):
    user=request.user
    qs = Profile.objects.get_all_profiles(user)
    context = {
        'qs':qs
    }
    return render(request, 'profiles/profile_list.html', context=context)

class ProfileListView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    # context_object_name = 'qs' 
    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user)
        profile = Profile.objects.get(user=user)
        # profile=Profile.objects.get(user__username__iexact=self.request.user)
        # context["profile"] = profile
        rel_r = Relationship.objects.filter(sender=profile)
        rel_s = Relationship.objects.filter(receiver=profile)
        rel_receiver = []
        rel_sender = []
        for item in rel_r:
             rel_receiver.append(item.receiver.user)

        for item in rel_s:
             rel_sender.append(item.sender.user)
        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
            
        return context

def send_invatation(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        
        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')

def remove_from_friends(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)
        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:my-profile-view')
    

bffbook/profiles/templates/profiles/my_invites.html
{% extends 'base.html' %}
{% block title %}
My invite
{% endblock title %}

{% block content %}

<ul>
    {% for item in qs %}
      <li>{{item}}</li>
    {% endfor %}
</ul>

{% endblock content %}

bffbook/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}
{% block title %}
My profile
{% endblock title %}
{% block content %}
<!--MODAL -->
<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Update your Profile
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url}}">
    </div>
    <div class="description">
      <div class="ui header">Provide some additional/newest info</div>
      <form action='' method='POST' class='ui form' enctype='multipart/form-data'>
        {% csrf_token %}
        {{form.as_p}}
      
        
    </div>
  </div>
  <div class="actions">
   
    <button type='submit' class="ui positive right labeled icon button">
      Update
      <i class="checkmark icon"></i>
    </button>
    </form>
  </div>
</div>


<div class='ui segment'>
    {% if confirm %}
    <div class="ui green message">Your profile has been updated</div>

    {% endif %}
    <h3>my profile: {{request.user}}</h3>
    <div class='ui grid'>
        <div class='row'>
            <div class='six wide column'>
                <img class='ui medium rounded image' src="{{profile.avatar.url}}"/>
                <div class='row mt-5'>
                <button class='ui secondary button' id='modal-btn'>Update your profile</button>
                </div>
            </div>
            <div class='ten wide column'>
                <table class='ui table'>
                    <tbody>
                        <tr>
                            <td>username</td>
                            <td>{{profile.user}}</td>
                        </tr>
                        <tr>
                            <td>first name</td>
                            <td>{{profile.first_name}}</td>
                        </tr>
                        <tr>
                            <td>last name</td>
                            <td>{{profile.last_name}}</td>
                        </tr>
                        <tr>
                            <td>bio</td>
                            <td>{{profile.bio}}</td>
                        </tr>
                         <tr>
                            <td>number of friends</td>
                            <td>{{profile.get_friends_no}}</td>
                        </tr>
                        <tr>
                            <td>friends</td>
                            <td>
                                <ul>
                                    {% for friend in profile.get_friends %}
                                    <li>{{friend}}</li>
                                    {% endfor %}
                                
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>number of posts</td>
                            <td>{{profile.get_posts_no}}</td>
                        </tr>
                        <tr>
                            <td>number of likes given</td>
                            <td>{{profile.get_likes_given_no}}</td>
                        </tr>
                        <tr>
                            <td>number of likes received</td>
                            <td>{{profile.get_likes_received_no}}</td>
                        </tr>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
     
</div>

{% endblock content %}

bffbook/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}
{% block title %}
All profiles
{% endblock title %}

{% block content %}
  {% if is_empty %}
  <h1>No profilesto interract with</h1>
  {% endif %}
  {% for obj in object_list %}
    <div class="ui segment">
      <div class="ui grid">
        <div class="row">
          <div class="three wide column">
            <img src="{{obj.avatar.url}}" alt="" class="ui small circular image">
          </div>
          <div class="thirteen wide column">
            <h3>{{obj.user}}</h3>
            <p>{{obj.bio}}</p>
            <button class="ui positive primary button mb-5 w-big">See profile</button>
            <br>
            {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
              <form action="{% url 'profiles:send-invite' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                  <button type="submit" class="ui positive basic button mb-5 w-big">
                    <i class="plus square icon"></i>
                    Add to friends
                  </button>
              </form>
            {% endif %}

            {% if obj.user in rel_receiver and request.user not in obj.friends.all %}
              <button class="ui disabled button mb-5 w-big">
                <i class="user icon"></i>
                Waiting for approval
              </button>    
            {% endif %}

            {% if request.user in obj.friends.all %}
              <form action="{% url 'profiles:remove-friend' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                <button type="submit" class="ui negative basic button mb-5 w-big">
                  <i class="minus square icon"></i>
                  Remove from friends
                </button>
              
              </form>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

{% endblock content %}

bffbook/profiles/templates/profiles/to_intive_list.html
{% extends 'base.html' %}
{% block title %}
Invite friends
{% endblock title %}

{% block content %}

<ul>
    {% for item in qs %}
      <li>{{item}}</li>
    {% endfor %}
</ul>

{% endblock content %}